name: base
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.1.0=py39h06a4308_0
  - conda-package-handling=1.8.1=py39h7f8727e_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cudnn=8.0.4=cuda11.1_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py39h06a4308_0
  - ipython=8.3.0=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.2.2=py39h06a4308_0
  - jupyter_core=4.10.0=py39h06a4308_0
  - kiwisolver=1.4.2=py39h295c915_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_0
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_0
  - libtiff=4.2.0=h2818925_1
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.12=h74e7548_2
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.1=py39h06a4308_1
  - matplotlib-base=3.5.1=py39ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py39h06a4308_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py39h22f2fdc_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=22.3.0=py39h295c915_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - ruamel.yaml=0.17.21=py39h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py39h5eee18b_1
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=61.2.0=py39h06a4308_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.3=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_1
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.64.0=py39h06a4308_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - urllib3=1.26.9=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.0.0
      - apptools==5.2.0
      - astunparse==1.6.3
      - bottleneck==1.4.2
      - cachetools==5.3.0
      - chex==0.1.3
      - configobj==5.0.8
      - diffrax==0.2.2
      - dm-tree==0.1.7
      - edt==2.3.2
      - envisage==6.1.1
      - equinox==0.9.2
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - flatbuffers==2.0
      - functorch==1.13.1
      - gast==0.4.0
      - google-auth==2.16.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.3
      - h5py==3.8.0
      - imageio-ffmpeg==0.4.7
      - importlib-metadata==6.0.0
      - iniconfig==2.0.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jaxtyping==0.2.11
      - joblib==1.3.2
      - keopscore==2.1.1
      - keras==2.11.0
      - libclang==15.0.6.1
      - markdown==3.4.1
      - markupsafe==2.1.2
      - mayavi==4.8.1
      - medpy==0.4.0
      - meshlib==2.3.8.21
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - numexpr==2.10.2
      - numpy==1.26.4
      - numpy-stl==3.0.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - opencv-python-headless==4.7.0.72
      - openpyxl==3.1.1
      - opt-einsum==3.3.0
      - optax==0.1.2
      - pandas==2.2.3
      - pip==24.3.1
      - plotly==5.18.0
      - pluggy==1.5.0
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybind11==2.10.3
      - pyface==7.4.4
      - pykeops==2.1.1
      - pymeshlab==2022.2.post2
      - pyntcloud==0.3.1
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.11.1
      - pyreadstat==1.2.7
      - pytest==8.3.4
      - python-utils==3.5.2
      - python-version==0.0.2
      - pywavefront==1.3.3
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.3.1
      - scikit-spatial==6.8.0
      - scipy==1.13.1
      - simpleitk==2.2.1
      - stl==0.0.3
      - stripy==2.3.3
      - sympy==1.11.1
      - tenacity==8.2.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.2.0
      - threadpoolctl==3.2.0
      - tomli==2.2.1
      - toolz==0.11.2
      - torch==1.13.1
      - torchode==0.1.6
      - torchtyping==0.1.4
      - traits==6.4.1
      - traitsui==7.4.3
      - trimesh==3.20.1
      - typeguard==2.13.3
      - typing-extensions==4.2.0
      - tzdata==2024.2
      - vtk==9.2.6
      - werkzeug==2.2.3
      - wrapt==1.15.0
      - zipp==3.15.0
prefix: /home/ap2746/miniconda3
